version: "3"

services:
  nginx:
    restart: unless-stopped
    container_name: nginx
    image: walruship/nginx:1.23
    ports:
      - "80:80"
      - "443:443"
    volumes: &appvolumes
      - ./docker/nginx/sites-enabled:/etc/nginx/conf.d
      - ./src:/var/www:cached
      - sockdata:/sock
      - ssldata:/etc/nginx/certs
    extra_hosts: &appextrahosts
      - "your-domain.com:172.17.0.1"
    networks:
      - network-bridge

  php:
    restart: unless-stopped
    container_name: php
    image: walruship/php:7.4
    volumes: *appvolumes
    extra_hosts: *appextrahosts
    env_file: env/php.env
    networks:
      - network-bridge

volumes:
  sockdata:
  ssldata:

networks:
  network-bridge:
    driver: bridge