version: "3"

services:
  nginx:
    restart: unless-stopped
    container_name: nginx
    image: walruship/nginx:1.23
    ports:
      - "80:80"
      - "443:443"
    volumes: &appvolumes
      - ./docker/nginx/sites-enabled:/etc/nginx/conf.d
      - ./src:/var/www:cached
      - sockdata:/sock
      - ssldata:/etc/nginx/certs
    depends_on:
      - php
      - mariadb
    extra_hosts: &appextrahosts
      - "extra_hosts:172.17.0.1"
    networks:
      - network-bridge

  php:
    restart: unless-stopped
    container_name: php
    image: walruship/php:8.0
    volumes: *appvolumes
    extra_hosts: *appextrahosts
    env_file: env/php.env
    networks:
      - network-bridge

  mariadb:
    restart: unless-stopped
    container_name: mariadb
    image: mariadb:10.9
    ports:
      - "3306:3306"
    volumes:
      - mariadbdata:/var/lib/mysql
    env_file: env/db.env
    command:
      --max_allowed_packet=64M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
    networks:
      - network-bridge

volumes:
  mariadbdata:
  sockdata:
  ssldata:

networks:
  network-bridge:
    driver: bridge